### ISSUE TITLE
FTBFS: Installation issue: escalate->eictoymodel->opencascade

### ISSUE THREAD

**Issue by DraTeots** [eic/eic-spack#11] opened 2020-06-28 07:59 UTC
### Steps to reproduce the issue

```console
$ spack install eictoymodel
```

### Information on your system

Ubuntu 18-04 via WSL2 (lightweight virtual machine under Windows host system)

```
uname -a 
Linux RyzenX399 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional information

```
Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/home/romanov/eic/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/opencascade-7.4.0-7s3rl4fl6kox67u3lonpjhofxafqaz5v' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/home/romanov/eic/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/opencascade-7.4.0-7s3rl4fl6kox67u3lonpjhofxafqaz5v/lib;/home/romanov/eic/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/opencascade-7.4.0-7s3rl4fl6kox67u3lonpjhofxafqaz5v/lib64' '-DCMAKE_PREFIX_PATH:STRING=/home/romanov/eic/spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/cmake-3.17.1-b4dfaawhai3kun4hckgqbxb4f2cvoxsu' '-DUSE_TBB=OFF' '-DUSE_VTK=OFF' '-DUSE_FREEIMAGE=OFF' '-DUSE_RAPIDJSON=OFF' '/tmp/romanov/spack-stage/spack-stage-opencascade-7.4.0-7s3rl4fl6kox67u3lonpjhofxafqaz5v/spack-src'

1 error found in build log:
     46    This warning is for project developers.  Use -Wno-dev to suppress it.
     47
     48    -- Could NOT find Tclsh (missing: TCL_TCLSH)
     49    -- Info: Freetype is used by OCCT
     50    -- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1")
     51    -- Info: TKIVtk and TKIVtkDraw toolkits excluded due to VTK usage is disabled
  >> 52    CMake Error at CMakeLists.txt:726 (message):
     53      Could not find headers of used third-party products:
     54      3RDPARTY_TCL_INCLUDE_DIR 3RDPARTY_TK_INCLUDE_DIR
```

That is all I found on this error

https://www.opencascade.com/content/build-occt-without-tcltk-third-party-dependency

**Comment by wdconinc** [comment] 2020-06-28 18:23
This seems like an upstream issue. I'll test, try to reproduce and report upstream. What are your externals? Just the gcc or more than that? I'm surprised for example that it picked a local freetype instead of a spack version.

**Comment by DraTeots** [comment] 2020-06-29 02:13
Just gcc. So it is almost pure ubuntu

**Comment by DraTeots** [comment] 2020-06-29 04:50
If I do

```
spack install font-utils
```
it fixes the issue...

**Comment by wdconinc** [comment] 2020-07-01 23:29
Reproducible in spack-builder:ubuntu18.04. Will submit a merge request upstream. Just need to figure out what is typically pulled in.

**Comment by wdconinc** [comment] 2020-07-01 23:48
Minimal additional depends_on are tcl, tk, freetype (unsurprisingly). Only tk is objectionable due to large number of dependencies.

**Comment by wdconinc** [comment] 2020-07-01 23:55
Seems not possible to turn off with -DUSE_TCL=OFF or -DUSE_FREETYPE=OFF.

**Comment by wdconinc** [comment] 2020-07-02 00:32
Also depends_on gl through #include GL/glx.h

**Comment by wdconinc** [comment] 2020-07-02 01:31
Sheesh, gl pulls in mesa and llvm. Gonna take a while.

**Comment by wdconinc** [comment] 2020-07-02 19:40
Reported upstream https://github.com/spack/spack/pull/17357

**Comment by wdconinc** [comment] 2020-07-05 21:03
Resolved upstream. Fix is in spack branch develop and next spack release after 0.15.

**Closed by wdconinc** 2020-07-05 21:03 UTC
Labels: ftbfs, upstream
